---
title: "20191114_survey_analysis"
author: "Lucas Kampman"
date: "11/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Set WD:

```{r cars}
setwd("/Users/lucaskampman/Box Sync/moorea_docs/")
```

## PCA of survey data

Beginning by reading in the data as plot_data:

```{r pressure}
plot_data<- read.csv("kampman_plot_data.csv")

summary(plot_data)

# Filter out data that's only in the barrier:

library(dplyr)
barrier_data <- filter(plot_data, plot_desc == "north_barrier")

summary(barrier_data)

# Import vegan for NMDS stuff

library(vegan)

# Include only certain columns for pairwise comparison:

plot_data_skinny <- plot_data[c("plot_depth_mean","L_count","P_count","A_count",
                                  "plot_lat_decimal","plot_long_decimal","general_substrate",
                                "dist_to_channel_m","perc_coral_heads",
                                  "padina_present", "sarg_present","turb_present","hal_present","turbidity","should_use")]

# Exclude rows with NA's (for NMDS)

plot_data_skinny <- na.omit(plot_data_skinny)

# pull out rows for plots where there were no organisms (i.e. row sum is 0)
plot_data_skinny <- plot_data_skinny[(plot_data_skinny$should_use == "use"),]

# look at it
pairs(plot_data_skinny,lower.panel = NULL,cex=.1)


# split into environmental and community data

environmental_data <- plot_data_skinny[c("plot_depth_mean","dist_to_channel_m","perc_coral_heads","general_substrate","turbidity")]
community_data <- plot_data_skinny[c("L_count","P_count","A_count","padina_present", "sarg_present","turb_present","hal_present")]


# Rename columns so they're not as bad

library(tidyverse)
environmental_data <- environmental_data %>% rename(
  "depth" = plot_depth_mean,
  "distance to channel" = dist_to_channel_m,
  "coral cover" = perc_coral_heads,
  "substrate: " = general_substrate,
  "turbidity:" = turbidity
)

community_data <- community_data %>% rename(
  "Lyngbya" = L_count,
  "Plurispecific" = P_count,
  "Anabaena" = A_count,
  "Padina" = padina_present,
  "Sargassum" = sarg_present,
  "Turbinaria" = turb_present,
  "Halimeda" = hal_present
  )


# Run CCA, plot it

vare_cca <- cca(community_data,environmental_data)
summary(vare_cca)
plot(vare_cca)

# for plotting CCA in ggplot2, code taken from https://blogs.ncl.ac.uk/mep/2018/04/08/reproducible-publication-quality-multivariate-plots-in-r/

library(vegan)
library(tidyverse)
library(ggrepel)
vare_spp_sco <- scores(vare_cca, display = "species")
vare_sam_sco <- scores(vare_cca, display = "sites")
vare_env_sco <- scores(vare_cca, display = "bp")
vare_spp_tbl <- as_tibble(vare_spp_sco)
vare_sam_tbl <- as_tibble(vare_sam_sco)
vare_env_tbl <- as_tibble(vare_env_sco)
vare_spp_tbl <- mutate(vare_spp_tbl, vgntxt=rownames(vare_spp_sco),
                       ccatype = "species")
vare_sam_tbl <- mutate(vare_sam_tbl, vgntxt=rownames(vare_sam_sco),
                       ccatype = "sites")
vare_env_tbl <- mutate(vare_env_tbl, vgntxt=rownames(vare_env_sco),
                       ccatype = "bp")

vare_sam_sco

write.csv(file="tempfile.csv",plot_data_skinny)

cca_lat_long <- plot_data_skinny
cca_lat_long$CCA1 <- vare_sam_sco[,1]
cca_lat_long$CCA2 <- vare_sam_sco[,2]

cca_lat_long

plt <- ggplot(vare_spp_tbl, aes(x = CCA1, y = CCA2, label = vgntxt)) +
       geom_point() +
       geom_text_repel(seed = 123)
plt


rescaled <- vare_env_tbl %>% 
            select(CCA1, CCA2) %>%
            as.matrix() * 1.5
vare_tbl <- select(vare_env_tbl, vgntxt, ccatype) %>%
            bind_cols(as_tibble(rescaled)) %>%
            bind_rows(vare_spp_tbl)

critval <- 0.1 #0.5
vare_tbl<- vare_tbl %>%
           mutate(vgntxt=ifelse(CCA1 < critval & CCA1 > -critval &
                                CCA2 < critval & CCA2 > -critval &
                                ccatype=="species", "", vgntxt))

cca_plot <- ggplot() +
  geom_point(aes(x=CCA1, y=CCA2), data=filter(vare_tbl, ccatype=="species"))  +
  geom_text_repel(aes(x=CCA1, y=CCA2,label.padding = 1 , label=vgntxt, size=3.5, colour=ccatype),
                  data=vare_tbl, seed=1234, force = 10) + 
  geom_segment(aes(x=0, y=0, xend=CCA1, yend=CCA2), arrow=arrow(length = unit(0.2,"cm")), 
               data=filter(vare_tbl, ccatype=="bp"), color="blue") +
  coord_fixed() +
  scale_colour_manual(values = c("blue", "black")) +
  theme_classic() +
  theme(legend.position="none")+
  theme(axis.text=element_text(size=13),axis.title=element_text(size=15))



cca_plot


cca_plot_big <- ggplot() +
  geom_point(aes(x=CCA1, y=CCA2), data=filter(vare_tbl, ccatype=="species"))  +
  geom_text_repel(aes(x=CCA1, y=CCA2,label.padding = 1 , label=vgntxt, size=10.5, colour=ccatype),
                  data=vare_tbl, seed=1234, force = 10) + 
  geom_segment(aes(x=0, y=0, xend=CCA1, yend=CCA2), arrow=arrow(length = unit(0.2,"cm")), 
               data=filter(vare_tbl, ccatype=="bp"), color="blue") +
  coord_fixed() +
  scale_colour_manual(values = c("blue", "black")) +
  theme_classic() +
  theme(legend.position="none")+
  theme(axis.text=element_text(size=15),axis.title=element_text(size=17))

ggsave("cca_plot_big_text.pdf", cca_plot_big)

# 
# ggplot() +
# geom_point(aes(x=CCA1, y=CCA2, color = ccatype), data=filter(vare_tbl, ccatype=="species"| ccatype== "cn")) +
# geom_text_repel(aes(x=CCA1, y=CCA2, label=vgntxt, size=3.5, colour=ccatype),
# data=vare_tbl, seed=123) +
#   geom_point(aes(x=CCA1, y=CCA2), data=filter(mbc_sam_tbl, ccatype="sites")) +
# geom_segment(aes(x=0, y=0, xend=CCA1, yend=CCA2), arrow=arrow(length = unit(0.2,"cm")),
# data=filter(vare_tbl, ccatype=="bp"), color="blue") +
# coord_fixed() +
# scale_colour_manual(values = c("blue", "red", "black")) +
# theme_classic() +
# theme(legend.position="none")

# trying to map everything and plot it as a single figure
#
#
# a source: https://rpubs.com/kohske/6886
# another: https://cran.r-project.org/web/packages/egg/vignettes/Ecosystem.html
#


library(ggmap)
library(tmaptools)
library(viridis)
library(lubridate)
library(ggplot2)

site_location <- c(-149.845, -17.505, -149.81,-17.475)
# site_center <- c(-149.827,-17.495)
# ggmap(get_stamenmap(rbind(as.numeric(paste(geocode_OSM("Moorea")$bbox))), zoom = 12)) +
#   geom_point(data =cca_lat_long,aes(y=plot_lat_decimal,x=plot_long_decimal, color=CCA1),alpha=0.5,size=1) + scale_color_viridis(option="magma")

# 
# cca1_map <- ggmap(get_stamenmap(site_location,  zoom=14)) +
#   geom_point(data =cca_lat_long,aes(y=plot_lat_decimal,x=plot_long_decimal, color=CCA1),alpha=0.5,size=2.5) + scale_color_viridis(option="magma")
# 
# cca2_map <- ggmap(get_stamenmap(site_location,  zoom=14)) +
#   geom_point(data =cca_lat_long,aes(y=plot_lat_decimal,x=plot_long_decimal, color=CCA2),alpha=0.5,size=2.5) + scale_color_viridis(option="magma") +
#   theme(axis.text=element_text(size=15),axis.title=element_text(size=18))

cca1_map <- ggmap(get_stamenmap(site_location,  zoom=14)) +
  geom_point(data =cca_lat_long,aes(y=plot_lat_decimal,x=plot_long_decimal, color=CCA1),alpha=0.5,size=2.5) + scale_color_viridis(option="magma") +
  theme(axis.text=element_text(size=12),axis.title=element_text(size=15)) + xlab("Longitude") + ylab("Latitude") +
  theme(legend.title = element_text(size=12), legend.text = element_text(size =11))

ggsave("cca1_map.pdf", cca1_map)

cca2_map <- ggmap(get_stamenmap(site_location,  zoom=14)) +
  geom_point(data =cca_lat_long,aes(y=plot_lat_decimal,x=plot_long_decimal, color=CCA2),alpha=0.5,size=2.5) + scale_color_viridis(option="magma") +
  theme(axis.text=element_text(size=12),axis.title=element_text(size=15)) + xlab("Longitude") + ylab("Latitude") +
  theme(legend.title = element_text(size=12), legend.text = element_text(size =11))

ggsave("cca2_map.pdf", cca2_map)


library(gtable)
library(ggplot2)
library(grid)
library(egg)

# 
# cca_plot_grob <- ggplotGrob(cca_plot)
# cca1grob <- ggplotGrob(cca1_map)
# cca2grob <- ggplotGrob(cca2_map)
# 
# cca_fig <- cbind(cca_plot_grob, cca1grob, cca2grob, size = "first")
# 
# library(gridExtra)
cca_fig <- ggarrange(cca_plot, cca1_map, cca2_map, nrow = 3, ncol = 1)

ggsave("cca_stuff.pdf", width = 6, height = 15, cca_fig)


# Run a PCA, plot it

plot_data_pca <- plot_data_skinny[c("plot_depth_mean","L_count","P_count","A_count",
                                  "plot_lat_decimal","plot_long_decimal",
                                "dist_to_channel_m","perc_coral_heads",
                                  "padina_present", "sarg_present","turb_present","hal_present","turbidity")]
plot_data_pca
# vare_pca <- princomp(~.,data=plot_data_pca) 
# summary(vare_pca)
# vare_pca


```

## Analysis of individual BCM data

Here I'd like to analyze the data I took for individual BCMs (size, substrate), and see what I can find.

```{r}
bcm_data <- read.csv("kampman_bcm_data.csv")
library(tidyverse)

# trim

bcm_data_skinny <- na.omit(bcm_data)

plot_gathered <- plot_data_skinny %>% 
  group_by(plot_depth_mean) %>% 
  gather(species, count_by_species, L_count:A_count)
  
# View(plot_gathered)

library(ggplot2)
library(ggthemes)
library(viridis)

head(bcm_data_skinny)

ggplot(plot_gathered, aes(x = plot_depth_mean, y = count_by_species, color = species)) + 
  geom_point() + theme_hc() + scale_color_hc(labels = c("Anabaena", "Lyngbya", "Plurispecific")) + 
  # ggtitle("Cyanobacterial mat abundance versus depth") + 
  theme(plot.title = element_text(size = 26), axis.title.x = element_text(size =21), axis.title.y = element_text(size = 21), axis.text=element_text(size=15)) + 
  geom_smooth(se = FALSE) +
  ylab("Number of Mats") + xlab("Depth (cm)") + ylim(-5, 45) + theme(legend.text=element_text(size=18), legend.title=element_blank())
ggsave("abundance--plot_depth_mean.pdf", height = 4.5, width = 7)

ggplot(plot_gathered, aes(x = dist_to_channel_m, y = count_by_species, color = species)) + 
  geom_point() + theme_hc() + scale_color_hc(labels = c("Anabaena", "Lyngbya", "Plurispecific")) + 
  ggtitle("Cyanobacterial mat abundance versus distance to channel") + 
  theme(plot.title = element_text(size = 20), axis.title.x = element_text(size = 16), axis.title.y = element_text(size = 16)) + 
  geom_smooth(se = FALSE) +
  ylab("Number of Mats") + xlab("Distance to channel (m)") + ylim(-5, 45)
ggsave("abundance--dist_to_channel_m.pdf")

ggplot(plot_gathered, aes(x = plot_long_decimal, y = count_by_species, color = species)) + 
  geom_point() + theme_hc() + scale_color_hc(labels = c("Anabaena", "Lyngbya", "Plurispecific")) + 
  ggtitle("BCM abundance versus longitude") + 
  theme(plot.title = element_text(size = 20), axis.title.x = element_text(size = 16), axis.title.y = element_text(size = 16)) + 
  geom_smooth(se = FALSE) + ylab("Number of Mats") + xlab("Longitude") + ylim(-5, 45)
ggsave("abundance--plot_lat_decimal.pdf")

ggplot(plot_gathered, aes(x = perc_coral_heads, y = count_by_species, color = species)) + 
  geom_point() + theme_hc() + scale_color_hc(labels = c("Anabaena", "Lyngbya", "Plurispecific")) + 
  ggtitle("BCM abundance versus percent coral head coverage") + 
  theme(plot.title = element_text(size = 20), axis.title.x = element_text(size = 16), axis.title.y = element_text(size = 16)) + 
  stat_smooth(method = "lm", formula = y ~ poly(x, 2), size = 1, se=FALSE) + ylim(-5, 45)
ggsave("abundance--perc_coral_heads.pdf")


```

## Analyzing contributing factors to bcm data:


```{r}
library(lme4)
library(lmerTest)

head(plot_data_skinny)

l_explanatory_fit_full <- glm(L_count ~ 
                             plot_lat_decimal + plot_long_decimal + 
                             plot_depth_mean + dist_to_channel_m +
                             padina_present + perc_coral_heads +
                             sarg_present + turb_present + hal_present,
                           data = plot_data_skinny, family = poisson)
l_explanatory_fit_reduced_ <- glm(L_count ~ 
                             plot_lat_decimal + plot_long_decimal + 
                             plot_depth_mean  +
                             padina_present + perc_coral_heads +
                             sarg_present + turb_present + hal_present,
                           data = plot_data_skinny, family = poisson)
# anova(l_explanatory_fit_reduced, l_explanatory_fit_full, test = "F")

l_explanatory_fit_reduced_sarg <- glm(L_count ~ 
                             plot_lat_decimal + plot_long_decimal + 
                             plot_depth_mean + dist_to_channel_m +
                             padina_present + perc_coral_heads +
                              turb_present + hal_present,
                           data = plot_data_skinny, family = poisson)
anova(l_explanatory_fit_reduced_sarg, l_explanatory_fit_full, test = "F")

l_explanatory_fit_reduced_ <- glm(L_count ~ 
                             plot_lat_decimal + plot_long_decimal + 
                             plot_depth_mean + dist_to_channel_m +
                             padina_present + perc_coral_heads +
                             sarg_present + turb_present + hal_present,
                           data = plot_data_skinny, family = poisson)
anova(l_explanatory_fit_reduced_, l_explanatory_fit_full, test = "F")

l_explanatory_fit_reduced_ <- glm(L_count ~ 
                             plot_lat_decimal + plot_long_decimal + 
                             plot_depth_mean + dist_to_channel_m +
                             padina_present + perc_coral_heads +
                             sarg_present + turb_present + hal_present,
                           data = plot_data_skinny, family = poisson)
anova(l_explanatory_fit_reduced_, l_explanatory_fit_full, test = "F")

l_explanatory_fit_reduced_ <- glm(L_count ~ 
                             plot_lat_decimal + plot_long_decimal + 
                             plot_depth_mean + dist_to_channel_m +
                             padina_present + perc_coral_heads +
                             sarg_present + turb_present + hal_present,
                           data = plot_data_skinny, family = poisson)
anova(l_explanatory_fit_reduced_, l_explanatory_fit_full, test = "F")


summary(l_explanatory_fit_full)

p_explanatory_fit <- glm(P_count ~ 
                             plot_lat_decimal + plot_long_decimal + 
                             plot_depth_mean + dist_to_channel_m +
                             padina_present + perc_coral_heads +
                             sarg_present + turb_present + hal_present,
                           data = plot_data_skinny, family = poisson)
summary(p_explanatory_fit)

a_explanatory_fit <- glm(A_count ~ 
                             plot_lat_decimal + plot_long_decimal + 
                             plot_depth_mean + dist_to_channel_m +
                             padina_present + perc_coral_heads +
                             sarg_present + turb_present + hal_present,
                           data = plot_data_skinny, family = poisson)
summary(a_explanatory_fit)

#
#
#
#

# now using the trimmed data set

head(bcm_data_skinny)

l_explanatory_fit <- glm(L_count ~ 
                             #plot_lat_decimal + plot_long_decimal + 
                             plot_depth_mean + dist_to_channel_m +
                             perc_coral_heads + 
                             padina_present + sarg_present + turb_present + hal_present #+ (1|bcm_index)
                           ,
                           data = plot_data_skinny, family = poisson)
summary(l_explanatory_fit)

p_explanatory_fit <- glm(P_count ~ 
                             #plot_lat_decimal + plot_long_decimal + 
                             plot_depth_mean + dist_to_channel_m +
                             padina_present + perc_coral_heads +
                             sarg_present + turb_present + hal_present,
                           data = plot_data_skinny, family = poisson)
summary(p_explanatory_fit)

a_explanatory_fit <- glm(A_count ~ 
                             #plot_lat_decimal + plot_long_decimal + 
                             plot_depth_mean + dist_to_channel_m +
                             padina_present + perc_coral_heads +
                             sarg_present + turb_present + hal_present,
                           data = plot_data_skinny, family = poisson)
summary(a_explanatory_fit)

length_explanatory_fit <- glm(bcm_length ~ 
                             #plot_lat_decimal + plot_long_decimal + 
                             plot_depth_mean + dist_to_channel_m +
                             padina_present + perc_coral_heads +
                             sarg_present + turb_present + hal_present,
                           data = filter(bcm_data_skinny, bcm_species == "p"), family = gaussian())
summary(length_explanatory_fit)

ggplot(bcm_data_skinny, aes(x = plot_depth_mean, y = bcm_length, color = bcm_species)) + geom_point() + 
  theme_hc() + scale_color_hc() + ggtitle("length over depth") + 
  theme(plot.title = element_text(size = 20), axis.title.x = element_text(size = 16), axis.title.y = element_text(size = 16)) + 
  geom_smooth(method = "lm", se = FALSE)

ggsave("bcm_indiv_length_vs_depth.pdf")

plot.new()
abline(glm(bcm_data_skinny$L_count ~ bcm_data_skinny$plot_depth_mean))
#summary(bcm_data$bcm_substrate)

```


